SELECT DISTINCT *
WHERE {
   ?drug1 <http://wifo5-04.informatik.uni-mannheim.de/drugbank/resource/drugbank/possibleDiseaseTarget> <http://wifo5-04.informatik.uni-mannheim.de/diseasome/resource/diseases/261> .
   ?drug1 <http://wifo5-04.informatik.uni-mannheim.de/drugbank/resource/drugbank/target> ?o.
    ?o <http://wifo5-04.informatik.uni-mannheim.de/drugbank/resource/drugbank/genbankIdGene> ?g.
?o <http://wifo5-04.informatik.uni-mannheim.de/drugbank/resource/drugbank/locus> ?l.
?o <http://wifo5-04.informatik.uni-mannheim.de/drugbank/resource/drugbank/molecularWeight> ?mw.
?o <http://wifo5-04.informatik.uni-mannheim.de/drugbank/resource/drugbank/hprdId> ?hp.
?drug <http://wifo5-04.informatik.uni-mannheim.de/drugbank/resource/drugbank/target>?o.
   ?drug <http://www.w3.org/2002/07/owl#sameAs> ?drug5 .}
ORDER BY ?drug
