select distinct * where {
?s1 <http://bio2rdf.org/geneid_vocabulary:has_locus_tag> ?lt1.
?s2 <http://bio2rdf.org/geneid_vocabulary:has_locus_tag> ?lt2.
?s3 <http://bio2rdf.org/geneid_vocabulary:has_locus_tag> ?lt3.
?s4 <http://bio2rdf.org/geneid_vocabulary:has_locus_tag> ?lt4.
?s5 <http://bio2rdf.org/geneid_vocabulary:has_locus_tag> ?lt5.
?s6 <http://bio2rdf.org/geneid_vocabulary:has_locus_tag> ?lt6.
?s1 <http://bio2rdf.org/geneid_vocabulary:has_taxid> ?o1.
?s1 <http://bio2rdf.org/geneid_vocabulary:has_genomic_nucleotide_gi> <http://bio2rdf.org/gi:116010291> .
?s1 <http://bio2rdf.org/geneid_vocabulary:has_map_location> ?l1.
?s1 <http://bio2rdf.org/geneid_vocabulary:has_nomenclature_status> ?st1.
?s1 <http://bio2rdf.org/geneid_vocabulary:has_nomenclature_authority> ?na.
?s2 <http://bio2rdf.org/geneid_vocabulary:has_genomic_nucleotide_gi> <http://bio2rdf.org/gi:113193577> .
?s2 <http://bio2rdf.org/geneid_vocabulary:has_taxid> ?o2.
?s2 <http://bio2rdf.org/geneid_vocabulary:has_map_location> ?l2.
?s2 <http://bio2rdf.org/geneid_vocabulary:has_nomenclature_status> ?st2.
?s2 <http://bio2rdf.org/geneid_vocabulary:has_nomenclature_authority> ?na.
?s3 <http://bio2rdf.org/geneid_vocabulary:has_taxid> ?o3.
?s3 <http://bio2rdf.org/geneid_vocabulary:has_genomic_nucleotide_gi> <http://bio2rdf.org/gi:194353639> .
?s3  <http://bio2rdf.org/geneid_vocabulary:has_map_location> ?l3.
?s3 <http://bio2rdf.org/geneid_vocabulary:has_nomenclature_status> ?st3.
?s3 <http://bio2rdf.org/geneid_vocabulary:has_nomenclature_authority> ?na.
?s4 <http://bio2rdf.org/geneid_vocabulary:has_taxid> ?o4.
?s4 <http://bio2rdf.org/geneid_vocabulary:has_genomic_nucleotide_gi> <http://bio2rdf.org/gi:223969116> .
?s4 <http://bio2rdf.org/geneid_vocabulary:has_nomenclature_authority> ?na.
?s4 <http://bio2rdf.org/geneid_vocabulary:has_map_location> ?l4.
?s4 <http://bio2rdf.org/geneid_vocabulary:has_nomenclature_status> ?st4.
?s5 <http://bio2rdf.org/geneid_vocabulary:has_taxid> ?o5.
?s5 <http://bio2rdf.org/geneid_vocabulary:has_genomic_nucleotide_gi> <http://bio2rdf.org/gi:194353643> .
?s5 <http://bio2rdf.org/geneid_vocabulary:has_nomenclature_authority> ?na.
?s5 <http://bio2rdf.org/geneid_vocabulary:has_map_location> ?l5.
?s5 <http://bio2rdf.org/geneid_vocabulary:has_nomenclature_status> ?st5.
?s6 <http://bio2rdf.org/geneid_vocabulary:has_taxid> ?o6.
?s6 <http://bio2rdf.org/geneid_vocabulary:has_genomic_nucleotide_gi> <http://bio2rdf.org/gi:223969120> .
?s6 <http://bio2rdf.org/geneid_vocabulary:has_nomenclature_authority> ?na.
?s6 <http://bio2rdf.org/geneid_vocabulary:has_map_location> ?l6.
?s6 <http://bio2rdf.org/geneid_vocabulary:has_nomenclature_status> ?st6.
}
