SELECT * WHERE {
?m <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://data.linkedmdb.org/resource/movie/writer>.
?t2 <http://data.linkedmdb.org/resource/movie/writer> ?m.
?t2 <http://data.linkedmdb.org/resource/movie/rating> <http://data.linkedmdb.org/resource/content_rating/11>.
}


