select distinct *
where {
?d1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?t1 .
?d2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?t2.
?d1 <http://dbpedia.org/property/emedicinetopic> ?o11.
?d2 <http://dbpedia.org/property/emedicinetopic> ?o12.
?d1 <http://dbpedia.org/ontology/medlineplus> ?m1.
?d2 <http://dbpedia.org/ontology/medlineplus> ?m2.
 OPTIONAL {
 ?d1 <http://dbpedia.org/ontology/meshId> ?ms1.
 ?d1 <http://dbpedia.org/ontology/omim> ?o1.
}.
 OPTIONAL {
?d2 <http://dbpedia.org/ontology/meshId> ?ms2.
 ?d2 <http://dbpedia.org/ontology/omim> ?o2.
}
FILTER (?t1 = <http://umbel.org/umbel/rc/AilmentCondition>)
FILTER (?t2 = <http://dbpedia.org/ontology/Disease>)
FILTER (?o11 = ?o12)
FILTER (?d1 != ?d2)
}
ORDER BY ?ss1
