select * where {
?s3 <http://epo.publicdata.eu/ebd/ontology/epoPublicationNumber> "1020899".
?s3 <http://epo.publicdata.eu/ebd/ontology/hasApplicationStatus> <http://epo.publicdata.eu/ebd/ontology/ApplicationStatusReplace> .
?s3 <http://epo.publicdata.eu/ebd/ontology/hasInvolvedCountry> ?hic3 .
?s3 <http://epo.publicdata.eu/ebd/ontology/hasPreviousChange> ?hpc3 .
?s3 <http://epo.publicdata.eu/ebd/ontology/publishedDate> ?pd3 .
}
