select ?pm
where {
?s1 <http://bio2rdf.org/pubmed_vocabulary:publication_type> 'JournalArticle'.
?s1 <http://bio2rdf.org/pubmed_vocabulary:owner> ?ow.
?s1 <http://bio2rdf.org/pubmed_vocabulary:author> ?o1.
?s1 <http://purl.org/dc/terms/identifier> ?i1.
?s1 <http://bio2rdf.org/pubmed_vocabulary:suppl_mesh_heading> ?mh1.
?s1 <http://purl.org/dc/terms/title> ?t1.
?s1 <http://bio2rdf.org/pubmed_vocabulary:publication_model> ?pm.
?s2  <http://bio2rdf.org/pubmed_vocabulary:publication_type> 'EvaluationStudies'.
?s2 <http://bio2rdf.org/pubmed_vocabulary:owner> ?ow.
?s2 <http://bio2rdf.org/pubmed_vocabulary:author> ?o2.
?s2 <http://purl.org/dc/terms/identifier> ?i2.
?s2 <http://purl.org/dc/terms/title> ?t2.
?s2 <http://bio2rdf.org/pubmed_vocabulary:publication_model> ?pm.
?s2 <http://bio2rdf.org/pubmed_vocabulary:suppl_mesh_heading> ?mh2.
}
ORDER BY ?pm
