select * where {
?s1 <http://bio2rdf.org/geneid_vocabulary:has_locus_tag> ?lt1.
?s1 <http://bio2rdf.org/geneid_vocabulary:has_taxid> ?o1.
?s1 <http://bio2rdf.org/geneid_vocabulary:has_genomic_nucleotide_gi> <http://bio2rdf.org/gi:116010291> .
?s1 <http://bio2rdf.org/geneid_vocabulary:has_map_location> ?l1.
?s1 <http://bio2rdf.org/geneid_vocabulary:has_nomenclature_status> ?st1.
?s1 <http://bio2rdf.org/geneid_vocabulary:has_nomenclature_authority> ?na.
?s1 <http://bio2rdf.org/geneid_vocabulary:has_pubmed_id> ?pubmed.
}
