select ?d where {
{
?s1 <http://www.w3.org/ns/dcat#keyword> "format-rdf" .
?s2 <http://www.w3.org/ns/dcat#keyword> "lod" .
?s1 <http://www.w3.org/ns/dcat#distribution> ?d .
?s2 <http://www.w3.org/ns/dcat#distribution> ?d .
?s1 <http://xmlns.com/foaf/0.1/homepage> ?h1.
?s2 <http://xmlns.com/foaf/0.1/homepage> ?h2.
?s1 <http://purl.org/dc/terms/relation> ?r1 .
?s2 <http://purl.org/dc/terms/relation> ?r2 .
FILTER (?s1!=?s2)
}
UNION
{
?s3 <http://www.w3.org/ns/dcat#keyword> "published-by-third-party" .
?s4 <http://www.w3.org/ns/dcat#keyword> "format-owl" .
?s3 <http://www.w3.org/ns/dcat#distribution> ?d .
?s3 <http://xmlns.com/foaf/0.1/homepage> ?h3.
?s3 <http://purl.org/dc/terms/relation> ?r3 .
?s4 <http://www.w3.org/ns/dcat#distribution> ?d .
?s4 <http://xmlns.com/foaf/0.1/homepage> ?h4.
?s4 <http://purl.org/dc/terms/relation> ?r4 .
FILTER (?s3!=?s4)
}
UNION
{
?s5 <http://www.w3.org/ns/dcat#keyword> "ontology" .
?s6 <http://www.w3.org/ns/dcat#keyword> "biomedicine" .
?s5 <http://www.w3.org/ns/dcat#distribution> ?d .
?s6 <http://www.w3.org/ns/dcat#distribution> ?d .
?s5 <http://xmlns.com/foaf/0.1/homepage> ?h5.
?s6 <http://xmlns.com/foaf/0.1/homepage> ?h6.
?s5 <http://purl.org/dc/terms/relation> ?r5 .
?s6 <http://purl.org/dc/terms/relation> ?r6 .
FILTER (?s5!=?s6)
}
}
ORDER BY ?d
