SELECT DISTINCT ?a WHERE {
?m1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://data.linkedmdb.org/resource/movie/writer>.
?t1 <http://data.linkedmdb.org/resource/movie/writer> ?m1.
OPTIONAL {
?t1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://data.linkedmdb.org/resource/movie/film>.
?t1 <http://data.linkedmdb.org/resource/movie/genre> ?o1.
?o1 <http://data.linkedmdb.org/resource/movie/film_genre_name> "Cult".
?t1 <http://data.linkedmdb.org/resource/movie/actor> ?a.
}
}

