SELECT ?a WHERE {
?m1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://data.linkedmdb.org/resource/movie/production_company>.
?m2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://data.linkedmdb.org/resource/movie/production_company>.
?t1 <http://data.linkedmdb.org/resource/movie/production_company> ?m1.
?t2 <http://data.linkedmdb.org/resource/movie/production_company> ?m2.
FILTER (?t2!=?t1)
OPTIONAL {
?t1 <http://data.linkedmdb.org/resource/movie/genre> ?o1.
?o1 <http://data.linkedmdb.org/resource/movie/film_genre_name> "Teen".
?t1 <http://data.linkedmdb.org/resource/movie/actor> ?a.
}.
OPTIONAL {
?t2 <http://data.linkedmdb.org/resource/movie/genre> ?o2.
?o2 <http://data.linkedmdb.org/resource/movie/film_genre_name> "Teen".
?t2 <http://data.linkedmdb.org/resource/movie/actor> ?a.
}
}
ORDER BY ?a
LIMIT 100
OFFSET 100

