select distinct ?t where {
{?s1 <http://bio2rdf.org/iproclass_vocabulary:x-pfam> <http://bio2rdf.org/pfam:PF04998> .
?s2 <http://bio2rdf.org/iproclass_vocabulary:x-pfam> <http://bio2rdf.org/pfam:PF11523> .
?s1 <http://bio2rdf.org/iproclass_vocabulary:x-genbank> ?g1.
?s2 <http://bio2rdf.org/iproclass_vocabulary:x-genbank> ?g2.
?s1 <http://bio2rdf.org/iproclass_vocabulary:x-gi> ?xg1 .
?s2 <http://bio2rdf.org/iproclass_vocabulary:x-gi> ?xg2 .
?s1 <http://bio2rdf.org/iproclass_vocabulary:x-geneid> ?gn1.
?s2 <http://bio2rdf.org/iproclass_vocabulary:x-geneid> ?gn2.
?s1 <http://bio2rdf.org/iproclass_vocabulary:x-refseq> ?xr1.
?s2 <http://bio2rdf.org/iproclass_vocabulary:x-refseq> ?xr2.
?s1 <http://bio2rdf.org/iproclass_vocabulary:x-taxon> ?t.
?s2 <http://bio2rdf.org/iproclass_vocabulary:x-taxon> ?t.
}
UNION
{?s3 <http://bio2rdf.org/iproclass_vocabulary:x-pfam> <http://bio2rdf.org/pfam:PF04983> .
 ?s4 <http://bio2rdf.org/iproclass_vocabulary:x-pfam> <http://bio2rdf.org/pfam:PF04997> .
?s3 <http://bio2rdf.org/iproclass_vocabulary:x-genbank> ?g3.
?s4 <http://bio2rdf.org/iproclass_vocabulary:x-genbank> ?g4.
?s3 <http://bio2rdf.org/iproclass_vocabulary:x-uniprot> ?xu3 .
?s4 <http://bio2rdf.org/iproclass_vocabulary:x-uniprot> ?xu4 .
?s3 <http://bio2rdf.org/iproclass_vocabulary:x-geneid> ?gn3.
?s4 <http://bio2rdf.org/iproclass_vocabulary:x-geneid> ?gn4.
?s3 <http://bio2rdf.org/iproclass_vocabulary:x-refseq> ?xr3.
?s4 <http://bio2rdf.org/iproclass_vocabulary:x-refseq> ?xr4.
?s3 <http://bio2rdf.org/iproclass_vocabulary:x-taxon> ?t.
?s4 <http://bio2rdf.org/iproclass_vocabulary:x-taxon> ?t.
}
}