SELECT DISTINCT ?genesymbol ?expression ?sample ?factor ?species ?experiment  
WHERE {      
{?genesymbol <http://www.ontotext.com/owlim/lucene#myIndex> "tgfb1" . 
?geneid <http://bio2rdf.org/ns/bio2rdf:symbol> ?genesymbol .     
?geneid <http://bio2rdf.org/ns/bio2rdf:xTaxonomy> ?taxon .   
?taxon <http://www.w3.org/2000/01/rdf-schema#label> ?species .    
?listmember <http://www.kupkb.org/data/kupkb/hasDatabaseRef> ?geneid .
?geneid <http://bio2rdf.org/ns/uniprot:xProtein> ?uniprot .     
?listmember <http://www.kupkb.org/data/kupkb/hasExpression> ?expressionURI .  
?expressionURI <http://www.w3.org/2000/01/rdf-schema#label> ?expression .   
?compoundList <http://www.kupkb.org/data/kupkb/hasMember> ?listmember .    
?analysis <http://www.kupkb.org/data/kupkb/produces> ?compoundList .   
?analysis <http://www.kupkb.org/data/kupkb/annotatedWith> ?annotation .   
?analysis <http://www.kupkb.org/data/kupkb/analysisOf>  ?experiment  .  
?annotation <http://www.kupkb.org/data/kupkb/hasAnnotationRole> <http://www.kupkb.org/data/kupo/KUPO_0300008> . 
?annotation <http://www.kupkb.org/data/kupkb/bioMaterial> ?analyteBioMaterial . 
?analyteBioMaterial <http://www.w3.org/2000/01/rdf-schema#label> ?sample .}
UNION { ?annotation <http://www.kupkb.org/data/kupkb/hasDisease> ?analyteDiseaseURI . 
      ?analyteDiseaseURI <http://www.w3.org/2000/01/rdf-schema#label> ?factor } 
}