SELECT ?m1 WHERE {
?m1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?t1.
?m1 <http://data.linkedmdb.org/resource/movie/writer> ?w1.
?m1 <http://data.linkedmdb.org/resource/movie/actor> ?a1.
?m1 <http://data.linkedmdb.org/resource/movie/director> ?d1.
?m1 <http://data.linkedmdb.org/resource/movie/producer> ?p1.
FILTER (?t1=<http://data.linkedmdb.org/resource/movie/film>)
}
ORDER BY ?m1
LIMIT 100
OFFSET 100

