select distinct ?has where {
{
?s1 <http://epo.publicdata.eu/ebd/ontology/bulletinCountry> ?bc1.
?s1 <http://epo.publicdata.eu/ebd/ontology/bulletinFile> ?bf1 .
?s1 <http://epo.publicdata.eu/ebd/ontology/bulletinIdentifier> ?bi1 .
?s1 <http://epo.publicdata.eu/ebd/ontology/epoPublicationNumber> ?epn1.
?s1 <http://epo.publicdata.eu/ebd/ontology/hasApplicationStatus> ?has .
?s1 <http://epo.publicdata.eu/ebd/ontology/hasInvolvedCountry> ?hic1 .
?s1 <http://epo.publicdata.eu/ebd/ontology/hasPreviousChange> ?hpc1 .
?s1 <http://epo.publicdata.eu/ebd/ontology/placeOfApplication> <http://epo.publicdata.eu/ebd/ontology/applicationPlace/09> .
?s1 <http://epo.publicdata.eu/ebd/ontology/publishedDate> ?pd1 .
?s2 <http://epo.publicdata.eu/ebd/ontology/bulletinCountry> ?bc2.
?s2 <http://epo.publicdata.eu/ebd/ontology/bulletinFile> ?bf2 .
?s2 <http://epo.publicdata.eu/ebd/ontology/bulletinIdentifier> ?bi2 .
?s2 <http://epo.publicdata.eu/ebd/ontology/epoPublicationNumber> ?epn2.
?s2 <http://epo.publicdata.eu/ebd/ontology/hasApplicationStatus> ?has .
?s2 <http://epo.publicdata.eu/ebd/ontology/hasInvolvedCountry> ?hic2 .
?s2 <http://epo.publicdata.eu/ebd/ontology/hasPreviousChange> ?hpc2 .
?s2 <http://epo.publicdata.eu/ebd/ontology/placeOfApplication>  <http://epo.publicdata.eu/ebd/ontology/applicationPlace/10> .
?s2 <http://epo.publicdata.eu/ebd/ontology/publishedDate> ?pd2 .
}
UNION
{
?s3 <http://epo.publicdata.eu/ebd/ontology/bulletinCountry> ?bc3.
?s3 <http://epo.publicdata.eu/ebd/ontology/bulletinFile> ?bf3 .
?s3 <http://epo.publicdata.eu/ebd/ontology/bulletinIdentifier> ?bi3 .
?s3 <http://epo.publicdata.eu/ebd/ontology/epoPublicationNumber> ?epn3.
?s3 <http://epo.publicdata.eu/ebd/ontology/hasApplicationStatus> ?has .
?s3 <http://epo.publicdata.eu/ebd/ontology/hasInvolvedCountry> ?hic3 .
?s3 <http://epo.publicdata.eu/ebd/ontology/hasPreviousChange> ?hpc3 .
?s3 <http://epo.publicdata.eu/ebd/ontology/placeOfApplication> <http://epo.publicdata.eu/ebd/ontology/applicationPlace/11> .
?s3 <http://epo.publicdata.eu/ebd/ontology/publishedDate> ?pd3 .
?s4 <http://epo.publicdata.eu/ebd/ontology/bulletinCountry> ?bc4.
?s4 <http://epo.publicdata.eu/ebd/ontology/bulletinFile> ?bf4 .
?s4 <http://epo.publicdata.eu/ebd/ontology/bulletinIdentifier> ?bi4 .
?s4 <http://epo.publicdata.eu/ebd/ontology/epoPublicationNumber> ?epn4.
?s4 <http://epo.publicdata.eu/ebd/ontology/hasApplicationStatus> ?has .
?s4 <http://epo.publicdata.eu/ebd/ontology/hasInvolvedCountry> ?hic4 .
?s4 <http://epo.publicdata.eu/ebd/ontology/hasPreviousChange> ?hpc4 .
?s4 <http://epo.publicdata.eu/ebd/ontology/placeOfApplication> <http://epo.publicdata.eu/ebd/ontology/applicationPlace/12> .
?s4 <http://epo.publicdata.eu/ebd/ontology/publishedDate> ?pd4 .
}
UNION
{
?s5 <http://epo.publicdata.eu/ebd/ontology/bulletinCountry> ?bc5.
?s5 <http://epo.publicdata.eu/ebd/ontology/bulletinFile> ?bf5 .
?s5 <http://epo.publicdata.eu/ebd/ontology/bulletinIdentifier> ?bi5 .
?s5 <http://epo.publicdata.eu/ebd/ontology/epoPublicationNumber> ?epn5.
?s5 <http://epo.publicdata.eu/ebd/ontology/hasApplicationStatus> ?has .
?s5 <http://epo.publicdata.eu/ebd/ontology/hasInvolvedCountry> ?hic5 .
?s5 <http://epo.publicdata.eu/ebd/ontology/hasPreviousChange> ?hpc5 .
?s5 <http://epo.publicdata.eu/ebd/ontology/placeOfApplication> <http://epo.publicdata.eu/ebd/ontology/applicationPlace/13>  .
?s5 <http://epo.publicdata.eu/ebd/ontology/publishedDate> ?pd5 .
?s6 <http://epo.publicdata.eu/ebd/ontology/bulletinCountry> ?bc6.
?s6 <http://epo.publicdata.eu/ebd/ontology/bulletinFile> ?bf6 .
?s6 <http://epo.publicdata.eu/ebd/ontology/bulletinIdentifier> ?bi6 .
?s6 <http://epo.publicdata.eu/ebd/ontology/epoPublicationNumber> ?epn6.
?s6 <http://epo.publicdata.eu/ebd/ontology/hasApplicationStatus> ?has .
?s6 <http://epo.publicdata.eu/ebd/ontology/hasInvolvedCountry> ?hic6 .
?s6 <http://epo.publicdata.eu/ebd/ontology/hasPreviousChange> ?hpc6 .
?s6 <http://epo.publicdata.eu/ebd/ontology/placeOfApplication> <http://epo.publicdata.eu/ebd/ontology/applicationPlace/14>  .
?s6 <http://epo.publicdata.eu/ebd/ontology/publishedDate> ?pd6 .
}
}
