SELECT DISTINCT ?genesymbol
WHERE {   
{   
?geneid1 <http://bio2rdf.org/ns/bio2rdf:symbol> ?genesymbol .     
?geneid1 <http://bio2rdf.org/ns/bio2rdf:xTaxonomy> <http://bio2rdf.org/taxon:10090> . 
?geneid1 <http://bio2rdf.org/ns/bio2rdf:symbol> ?s1 .
?geneid2 <http://bio2rdf.org/ns/bio2rdf:symbol> ?genesymbol . 
?geneid2 <http://bio2rdf.org/ns/bio2rdf:symbol> ?s2 .    
?geneid2 <http://bio2rdf.org/ns/bio2rdf:xTaxonomy> <http://bio2rdf.org/taxon:10116> .
}
UNION
{ 
?geneid3 <http://bio2rdf.org/ns/bio2rdf:symbol> ?genesymbol . 
?geneid3 <http://bio2rdf.org/ns/bio2rdf:symbol> ?s3 .   
?geneid3 <http://bio2rdf.org/ns/bio2rdf:xTaxonomy> <http://bio2rdf.org/taxon:9615> .
?geneid4 <http://bio2rdf.org/ns/bio2rdf:symbol> ?genesymbol . 
?geneid4 <http://bio2rdf.org/ns/bio2rdf:symbol> ?s4 .    
?geneid4 <http://bio2rdf.org/ns/bio2rdf:xTaxonomy> <http://bio2rdf.org/taxon:9606> .
}
}
