SELECT * WHERE {      
?analysis <http://www.kupkb.org/data/kupkb/produces> ?compoundList .   
?analysis <http://www.kupkb.org/data/kupkb/annotatedWith> ?annotation .   
?analysis <http://www.kupkb.org/data/kupkb/analysisOf>  ?experiment  .  
}
